name: Build with mkosi

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up mkosi incremental cache
        uses: actions/cache@v4
        with:
          path: mkosi.cache
          key: v1-mkosi-incremental

      - name: Set up mkosi package cache
        uses: actions/cache@v4
        with:
          path: mkosi.pkgcache
          key: v1-mkosi-pkg

      - name: Set up mkosi
        uses: systemd/mkosi@main

      - name: Run mkosi
        run: |
          mkosi --cache-directory=mkosi.cache/ --package-cache-dir=mkosi.pkgcache/
      - uses: actions/upload-artifact@v4
        with:
            name: me3-test-os-image
            path: mkosi.output/me3-test-os_x86-64.raw
  setup-ami-builder:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: "Authenticate using Enhanced AuthFlow"
        uses: catnekaise/cognito-idpool-auth@main
        with:
          auth-flow: "enhanced"
          cognito-identity-pool-id: "eu-west-1:e981a34c-3d1f-485d-8aa9-308ba3aa5a59"
          aws-region: "eu-west-1" # Overrides AWS_REGION env var
          aws-account-id: "690169311973"
          set-in-environment: true

      - run: aws sts get-caller-identity
  cleanup:
    runs-on: ubuntu-latest
    needs:
      - build
    if: always()
    steps:
    - uses: geekyeggo/delete-artifact@v5
      with:
          name: me3-test-os-image