name: Build with mkosi

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up mkosi cache
        uses: actions/cache@v4
        with:
          path: mkosi.cache
          key: v1-mkosi

      - name: Set up mkosi
        uses: systemd/mkosi@main

      - name: Run mkosi
        run: mkosi

      - name: Install ec2-ami-tools
        run: sudo apt-get install -y ec2-ami-tools